target-version = "py311"

# Set the maximum line length to 88.
line-length = 88

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*/**/__init__.py",
]

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "C", # flake8-comprehensions
    "D", # pydocstyle
    "E", # pycodestyle error
    "F", # Pyflakes
    "I", # isort
    "W" # pycodestyle warning
]
ignore = [
    "D100", # Missing docstring in public package
    "D415" # First line should end with a period, question mark, or exclamation point
]

extend-select = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = ["B"]

[lint.pydocstyle]
convention = "google"
