exp_name: food-101
dataset_root: !!python/object/apply:pathlib.PosixPath
  - data/datasets/food-101
ckpt_root: !!python/object/apply:pathlib.PosixPath
  - weight
num_classes: 101
start_epoch: 1
epochs: 50
restart: false
seed: 42
print_freq: 100

defaults:
  - _self_
  - arch: mobilenet_v2
