exp_name: food-101
dataset_path: !!python/object/apply:pathlib.PosixPath
  - data/datasets/food-101
ckpt_path: !!python/object/apply:pathlib.PosixPath
  - weight
num_classes: 101
start_epoch: 1
epochs: 1
restart: false
workers: 16
seed: 1
print_freq: 100
apex: false
apex_opt_level: O1

defaults:
  - _self_
  - arch: mobilenet_v2
